//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcedureSqlAndEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ogr()
        {
            this.Tbl_Notlar = new HashSet<Tbl_Notlar>();
        }
    
        public int Ogr_Id { get; set; }
        public string Ogr_Ad { get; set; }
        public string Ogr_Soyad { get; set; }
        public string Ogr_Photo { get; set; }
        public string Kulup { get; set; }
        public string Sehir { get; set; }
        public Nullable<int> KulupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notlar> Tbl_Notlar { get; set; }
    }
}
